displayName=PvM Toolkit
author=Arber
description=Track PvM profit by monster with combat loot logs, supply costs, High Alch or market values, Slayer history, timers, cannon alerts, and drop reminders.
tags=pvm,combat,boss,bossing,slayer,slayertask,superior,potions,potiontimer,timer,infobox,prayer,inventory,cannon,loot,lootlog,combatloot,glow,highlight,xp,tracker,drops,stats,warnings,notifications,grounditems,droptimer,slayerlog,taskhistory,personalbest,profit,profittracker,cost,costtracker,supplies,highalch,geprice,overload,antifire,antivenom,deathspawn
version=1.4.4
plugins=com.arber.pvmtools.PvmToolsPlugin
build=standard
